/*
 * generated by Xtext
 */
package dk.itu.smdp2015.church;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfiguratorRuntimeModule extends dk.itu.smdp2015.church.AbstractConfiguratorRuntimeModule {

}
