/*
* generated by Xtext
*/
package dk.itu.smdp2015.church;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ConfiguratorUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.smdp2015.church.ui.internal.ConfiguratorActivator.getInstance().getInjector("dk.itu.smdp2015.church.Configurator");
	}
	
}
