/**
 * generated by Xtext
 */
package dk.itu.smdp2015.church.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class ConfiguratorQuickfixProvider extends DefaultQuickfixProvider {
}
