/*
* generated by Xtext
*/
package dk.itu.smdp2015.church.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ConfiguratorGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ConfiguratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Configurator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConfiguratorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cParametersAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cParametersAbstractParameterParserRuleCall_4_0 = (RuleCall)cParametersAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cParametersAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cParametersAbstractParameterParserRuleCall_5_1_0 = (RuleCall)cParametersAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Configurator:
		//	"configurator" name=ID description=STRING? "{" parameters+=AbstractParameter (","? parameters+=AbstractParameter)*
		//	"}";
		public ParserRule getRule() { return rule; }

		//"configurator" name=ID description=STRING? "{" parameters+=AbstractParameter (","? parameters+=AbstractParameter)* "}"
		public Group getGroup() { return cGroup; }

		//"configurator"
		public Keyword getConfiguratorKeyword_0() { return cConfiguratorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//parameters+=AbstractParameter
		public Assignment getParametersAssignment_4() { return cParametersAssignment_4; }

		//AbstractParameter
		public RuleCall getParametersAbstractParameterParserRuleCall_4_0() { return cParametersAbstractParameterParserRuleCall_4_0; }

		//(","? parameters+=AbstractParameter)*
		public Group getGroup_5() { return cGroup_5; }

		//","?
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//parameters+=AbstractParameter
		public Assignment getParametersAssignment_5_1() { return cParametersAssignment_5_1; }

		//AbstractParameter
		public RuleCall getParametersAbstractParameterParserRuleCall_5_1_0() { return cParametersAbstractParameterParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class AbstractParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractParameter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParameterGroupParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParameterParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractParameter:
		//	ParameterGroup | Parameter;
		public ParserRule getRule() { return rule; }

		//ParameterGroup | Parameter
		public Alternatives getAlternatives() { return cAlternatives; }

		//ParameterGroup
		public RuleCall getParameterGroupParserRuleCall_0() { return cParameterGroupParserRuleCall_0; }

		//Parameter
		public RuleCall getParameterParserRuleCall_1() { return cParameterParserRuleCall_1; }
	}

	public class ParameterGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParameterGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cVisibleIfKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Assignment cVisibilityAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cVisibilityExpressionParserRuleCall_3_0_1_0 = (RuleCall)cVisibilityAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cConstraintsKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Assignment cConstraintsAssignment_3_1_2 = (Assignment)cGroup_3_1.eContents().get(2);
		private final RuleCall cConstraintsConstraintParserRuleCall_3_1_2_0 = (RuleCall)cConstraintsAssignment_3_1_2.eContents().get(0);
		private final Group cGroup_3_1_3 = (Group)cGroup_3_1.eContents().get(3);
		private final Keyword cCommaKeyword_3_1_3_0 = (Keyword)cGroup_3_1_3.eContents().get(0);
		private final Assignment cConstraintsAssignment_3_1_3_1 = (Assignment)cGroup_3_1_3.eContents().get(1);
		private final RuleCall cConstraintsConstraintParserRuleCall_3_1_3_1_0 = (RuleCall)cConstraintsAssignment_3_1_3_1.eContents().get(0);
		private final Keyword cCommaKeyword_3_1_4 = (Keyword)cGroup_3_1.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_3_1_5 = (Keyword)cGroup_3_1.eContents().get(5);
		private final Group cGroup_3_2 = (Group)cUnorderedGroup_3.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cParametersAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cParametersAbstractParameterParserRuleCall_3_2_1_0 = (RuleCall)cParametersAssignment_3_2_1.eContents().get(0);
		private final Group cGroup_3_2_2 = (Group)cGroup_3_2.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_2_0 = (Keyword)cGroup_3_2_2.eContents().get(0);
		private final Assignment cParametersAssignment_3_2_2_1 = (Assignment)cGroup_3_2_2.eContents().get(1);
		private final RuleCall cParametersAbstractParameterParserRuleCall_3_2_2_1_0 = (RuleCall)cParametersAssignment_3_2_2_1.eContents().get(0);
		private final Keyword cCommaKeyword_3_2_3 = (Keyword)cGroup_3_2.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_3_2_4 = (Keyword)cGroup_3_2.eContents().get(4);
		
		//ParameterGroup:
		//	"group" name=ID description=STRING? (("visible-if" visibility=Expression)? & ("constraints" "{"
		//	constraints+=Constraint ("," constraints+=Constraint)* ","? "}")? & "{" parameters+=AbstractParameter (","?
		//	parameters+=AbstractParameter)* ","? "}");
		public ParserRule getRule() { return rule; }

		//"group" name=ID description=STRING? (("visible-if" visibility=Expression)? & ("constraints" "{" constraints+=Constraint
		//("," constraints+=Constraint)* ","? "}")? & "{" parameters+=AbstractParameter (","? parameters+=AbstractParameter)*
		//","? "}")
		public Group getGroup() { return cGroup; }

		//"group"
		public Keyword getGroupKeyword_0() { return cGroupKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//("visible-if" visibility=Expression)? & ("constraints" "{" constraints+=Constraint ("," constraints+=Constraint)* ","?
		//"}")? & "{" parameters+=AbstractParameter (","? parameters+=AbstractParameter)* ","? "}"
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }

		//("visible-if" visibility=Expression)?
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"visible-if"
		public Keyword getVisibleIfKeyword_3_0_0() { return cVisibleIfKeyword_3_0_0; }

		//visibility=Expression
		public Assignment getVisibilityAssignment_3_0_1() { return cVisibilityAssignment_3_0_1; }

		//Expression
		public RuleCall getVisibilityExpressionParserRuleCall_3_0_1_0() { return cVisibilityExpressionParserRuleCall_3_0_1_0; }

		//("constraints" "{" constraints+=Constraint ("," constraints+=Constraint)* ","? "}")?
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"constraints"
		public Keyword getConstraintsKeyword_3_1_0() { return cConstraintsKeyword_3_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1_1() { return cLeftCurlyBracketKeyword_3_1_1; }

		//constraints+=Constraint
		public Assignment getConstraintsAssignment_3_1_2() { return cConstraintsAssignment_3_1_2; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_3_1_2_0() { return cConstraintsConstraintParserRuleCall_3_1_2_0; }

		//("," constraints+=Constraint)*
		public Group getGroup_3_1_3() { return cGroup_3_1_3; }

		//","
		public Keyword getCommaKeyword_3_1_3_0() { return cCommaKeyword_3_1_3_0; }

		//constraints+=Constraint
		public Assignment getConstraintsAssignment_3_1_3_1() { return cConstraintsAssignment_3_1_3_1; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_3_1_3_1_0() { return cConstraintsConstraintParserRuleCall_3_1_3_1_0; }

		//","?
		public Keyword getCommaKeyword_3_1_4() { return cCommaKeyword_3_1_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_1_5() { return cRightCurlyBracketKeyword_3_1_5; }

		//"{" parameters+=AbstractParameter (","? parameters+=AbstractParameter)* ","? "}"
		public Group getGroup_3_2() { return cGroup_3_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_2_0() { return cLeftCurlyBracketKeyword_3_2_0; }

		//parameters+=AbstractParameter
		public Assignment getParametersAssignment_3_2_1() { return cParametersAssignment_3_2_1; }

		//AbstractParameter
		public RuleCall getParametersAbstractParameterParserRuleCall_3_2_1_0() { return cParametersAbstractParameterParserRuleCall_3_2_1_0; }

		//(","? parameters+=AbstractParameter)*
		public Group getGroup_3_2_2() { return cGroup_3_2_2; }

		//","?
		public Keyword getCommaKeyword_3_2_2_0() { return cCommaKeyword_3_2_2_0; }

		//parameters+=AbstractParameter
		public Assignment getParametersAssignment_3_2_2_1() { return cParametersAssignment_3_2_2_1; }

		//AbstractParameter
		public RuleCall getParametersAbstractParameterParserRuleCall_3_2_2_1_0() { return cParametersAbstractParameterParserRuleCall_3_2_2_1_0; }

		//","?
		public Keyword getCommaKeyword_3_2_3() { return cCommaKeyword_3_2_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_2_4() { return cRightCurlyBracketKeyword_3_2_4; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParameterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescriptionAssignment_2.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_3_0 = (Alternatives)cUnorderedGroup_3.eContents().get(0);
		private final Assignment cMandatoryAssignment_3_0_0 = (Assignment)cAlternatives_3_0.eContents().get(0);
		private final Keyword cMandatoryMandatoryKeyword_3_0_0_0 = (Keyword)cMandatoryAssignment_3_0_0.eContents().get(0);
		private final Keyword cOptionalKeyword_3_0_1 = (Keyword)cAlternatives_3_0.eContents().get(1);
		private final Group cGroup_3_1 = (Group)cUnorderedGroup_3.eContents().get(1);
		private final Keyword cVisibleIfKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cVisibilityAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cVisibilityExpressionParserRuleCall_3_1_1_0 = (RuleCall)cVisibilityAssignment_3_1_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cUnorderedGroup_3.eContents().get(2);
		private final Keyword cConstraintsKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_2_1 = (Keyword)cGroup_3_2.eContents().get(1);
		private final Assignment cConstraintsAssignment_3_2_2 = (Assignment)cGroup_3_2.eContents().get(2);
		private final RuleCall cConstraintsConstraintParserRuleCall_3_2_2_0 = (RuleCall)cConstraintsAssignment_3_2_2.eContents().get(0);
		private final Group cGroup_3_2_3 = (Group)cGroup_3_2.eContents().get(3);
		private final Keyword cCommaKeyword_3_2_3_0 = (Keyword)cGroup_3_2_3.eContents().get(0);
		private final Assignment cConstraintsAssignment_3_2_3_1 = (Assignment)cGroup_3_2_3.eContents().get(1);
		private final RuleCall cConstraintsConstraintParserRuleCall_3_2_3_1_0 = (RuleCall)cConstraintsAssignment_3_2_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_2_4 = (Keyword)cGroup_3_2.eContents().get(4);
		private final Group cGroup_3_3 = (Group)cUnorderedGroup_3.eContents().get(3);
		private final Keyword cValuesKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cValueRangeAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cValueRangeValueRangeParserRuleCall_3_3_1_0 = (RuleCall)cValueRangeAssignment_3_3_1.eContents().get(0);
		
		//Parameter:
		//	"parameter" name=ID description=STRING? ((mandatory?="mandatory" | "optional")? & ("visible-if"
		//	visibility=Expression)? & ("constraints" "{" constraints+=Constraint ("," constraints+=Constraint)* "}")? & "values"
		//	valueRange=ValueRange);
		public ParserRule getRule() { return rule; }

		//"parameter" name=ID description=STRING? ((mandatory?="mandatory" | "optional")? & ("visible-if" visibility=Expression)?
		//& ("constraints" "{" constraints+=Constraint ("," constraints+=Constraint)* "}")? & "values" valueRange=ValueRange)
		public Group getGroup() { return cGroup; }

		//"parameter"
		public Keyword getParameterKeyword_0() { return cParameterKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//description=STRING?
		public Assignment getDescriptionAssignment_2() { return cDescriptionAssignment_2; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_2_0() { return cDescriptionSTRINGTerminalRuleCall_2_0; }

		//(mandatory?="mandatory" | "optional")? & ("visible-if" visibility=Expression)? & ("constraints" "{"
		//constraints+=Constraint ("," constraints+=Constraint)* "}")? & "values" valueRange=ValueRange
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }

		//(mandatory?="mandatory" | "optional")?
		public Alternatives getAlternatives_3_0() { return cAlternatives_3_0; }

		//mandatory?="mandatory"
		public Assignment getMandatoryAssignment_3_0_0() { return cMandatoryAssignment_3_0_0; }

		//"mandatory"
		public Keyword getMandatoryMandatoryKeyword_3_0_0_0() { return cMandatoryMandatoryKeyword_3_0_0_0; }

		//"optional"
		public Keyword getOptionalKeyword_3_0_1() { return cOptionalKeyword_3_0_1; }

		//("visible-if" visibility=Expression)?
		public Group getGroup_3_1() { return cGroup_3_1; }

		//"visible-if"
		public Keyword getVisibleIfKeyword_3_1_0() { return cVisibleIfKeyword_3_1_0; }

		//visibility=Expression
		public Assignment getVisibilityAssignment_3_1_1() { return cVisibilityAssignment_3_1_1; }

		//Expression
		public RuleCall getVisibilityExpressionParserRuleCall_3_1_1_0() { return cVisibilityExpressionParserRuleCall_3_1_1_0; }

		//("constraints" "{" constraints+=Constraint ("," constraints+=Constraint)* "}")?
		public Group getGroup_3_2() { return cGroup_3_2; }

		//"constraints"
		public Keyword getConstraintsKeyword_3_2_0() { return cConstraintsKeyword_3_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_2_1() { return cLeftCurlyBracketKeyword_3_2_1; }

		//constraints+=Constraint
		public Assignment getConstraintsAssignment_3_2_2() { return cConstraintsAssignment_3_2_2; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_3_2_2_0() { return cConstraintsConstraintParserRuleCall_3_2_2_0; }

		//("," constraints+=Constraint)*
		public Group getGroup_3_2_3() { return cGroup_3_2_3; }

		//","
		public Keyword getCommaKeyword_3_2_3_0() { return cCommaKeyword_3_2_3_0; }

		//constraints+=Constraint
		public Assignment getConstraintsAssignment_3_2_3_1() { return cConstraintsAssignment_3_2_3_1; }

		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_3_2_3_1_0() { return cConstraintsConstraintParserRuleCall_3_2_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_2_4() { return cRightCurlyBracketKeyword_3_2_4; }

		//"values" valueRange=ValueRange
		public Group getGroup_3_3() { return cGroup_3_3; }

		//"values"
		public Keyword getValuesKeyword_3_3_0() { return cValuesKeyword_3_3_0; }

		//valueRange=ValueRange
		public Assignment getValueRangeAssignment_3_3_1() { return cValueRangeAssignment_3_3_1; }

		//ValueRange
		public RuleCall getValueRangeValueRangeParserRuleCall_3_3_1_0() { return cValueRangeValueRangeParserRuleCall_3_3_1_0; }
	}

	public class ValueRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ValueRange");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEnumeratedParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBoundedParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ValueRange:
		//	Enumerated | Bounded;
		public ParserRule getRule() { return rule; }

		//Enumerated | Bounded
		public Alternatives getAlternatives() { return cAlternatives; }

		//Enumerated
		public RuleCall getEnumeratedParserRuleCall_0() { return cEnumeratedParserRuleCall_0; }

		//Bounded
		public RuleCall getBoundedParserRuleCall_1() { return cBoundedParserRuleCall_1; }
	}

	public class EnumeratedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Enumerated");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValuesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValuesExpressionParserRuleCall_1_0 = (RuleCall)cValuesAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cValuesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cValuesExpressionParserRuleCall_2_1_0 = (RuleCall)cValuesAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Enumerated:
		//	"(" values+=Expression ("," values+=Expression)* ")";
		public ParserRule getRule() { return rule; }

		//"(" values+=Expression ("," values+=Expression)* ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//values+=Expression
		public Assignment getValuesAssignment_1() { return cValuesAssignment_1; }

		//Expression
		public RuleCall getValuesExpressionParserRuleCall_1_0() { return cValuesExpressionParserRuleCall_1_0; }

		//("," values+=Expression)*
		public Group getGroup_2() { return cGroup_2; }

		//","
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }

		//values+=Expression
		public Assignment getValuesAssignment_2_1() { return cValuesAssignment_2_1; }

		//Expression
		public RuleCall getValuesExpressionParserRuleCall_2_1_0() { return cValuesExpressionParserRuleCall_2_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}

	public class BoundedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Bounded");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLowerBoundAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLowerBoundExpressionParserRuleCall_1_0 = (RuleCall)cLowerBoundAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUpperBoundAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUpperBoundExpressionParserRuleCall_3_0 = (RuleCall)cUpperBoundAssignment_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Bounded:
		//	"[" lowerBound=Expression ";" upperBound=Expression "]";
		public ParserRule getRule() { return rule; }

		//"[" lowerBound=Expression ";" upperBound=Expression "]"
		public Group getGroup() { return cGroup; }

		//"["
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }

		//lowerBound=Expression
		public Assignment getLowerBoundAssignment_1() { return cLowerBoundAssignment_1; }

		//Expression
		public RuleCall getLowerBoundExpressionParserRuleCall_1_0() { return cLowerBoundExpressionParserRuleCall_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }

		//upperBound=Expression
		public Assignment getUpperBoundAssignment_3() { return cUpperBoundAssignment_3; }

		//Expression
		public RuleCall getUpperBoundExpressionParserRuleCall_3_0() { return cUpperBoundExpressionParserRuleCall_3_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}

	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cDescriptionKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cDescriptionAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_0_1_0 = (RuleCall)cDescriptionAssignment_0_1.eContents().get(0);
		private final Assignment cExprAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExprExpressionParserRuleCall_1_0 = (RuleCall)cExprAssignment_1.eContents().get(0);
		
		//Constraint:
		//	("description" description=STRING)? expr=Expression;
		public ParserRule getRule() { return rule; }

		//("description" description=STRING)? expr=Expression
		public Group getGroup() { return cGroup; }

		//("description" description=STRING)?
		public Group getGroup_0() { return cGroup_0; }

		//"description"
		public Keyword getDescriptionKeyword_0_0() { return cDescriptionKeyword_0_0; }

		//description=STRING
		public Assignment getDescriptionAssignment_0_1() { return cDescriptionAssignment_0_1; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_0_1_0() { return cDescriptionSTRINGTerminalRuleCall_0_1_0; }

		//expr=Expression
		public Assignment getExprAssignment_1() { return cExprAssignment_1; }

		//Expression
		public RuleCall getExprExpressionParserRuleCall_1_0() { return cExprExpressionParserRuleCall_1_0; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final RuleCall cDisjunctiveParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression:
		//	Disjunctive;
		public ParserRule getRule() { return rule; }

		//Disjunctive
		public RuleCall getDisjunctiveParserRuleCall() { return cDisjunctiveParserRuleCall; }
	}

	public class DisjunctiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Disjunctive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cConjunctiveParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorDisjunctiveOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightConjunctiveParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Disjunctive returns Expression:
		//	Conjunctive ({Binary.left=current} operator=DisjunctiveOperator right=Conjunctive)*;
		public ParserRule getRule() { return rule; }

		//Conjunctive ({Binary.left=current} operator=DisjunctiveOperator right=Conjunctive)*
		public Group getGroup() { return cGroup; }

		//Conjunctive
		public RuleCall getConjunctiveParserRuleCall_0() { return cConjunctiveParserRuleCall_0; }

		//({Binary.left=current} operator=DisjunctiveOperator right=Conjunctive)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.left=current}
		public Action getBinaryLeftAction_1_0() { return cBinaryLeftAction_1_0; }

		//operator=DisjunctiveOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//DisjunctiveOperator
		public RuleCall getOperatorDisjunctiveOperatorEnumRuleCall_1_1_0() { return cOperatorDisjunctiveOperatorEnumRuleCall_1_1_0; }

		//right=Conjunctive
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Conjunctive
		public RuleCall getRightConjunctiveParserRuleCall_1_2_0() { return cRightConjunctiveParserRuleCall_1_2_0; }
	}

	public class ConjunctiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Conjunctive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEqualityParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorConjunctiveOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightEqualityParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Conjunctive returns Expression:
		//	Equality ({Binary.left=current} operator=ConjunctiveOperator right=Equality)*;
		public ParserRule getRule() { return rule; }

		//Equality ({Binary.left=current} operator=ConjunctiveOperator right=Equality)*
		public Group getGroup() { return cGroup; }

		//Equality
		public RuleCall getEqualityParserRuleCall_0() { return cEqualityParserRuleCall_0; }

		//({Binary.left=current} operator=ConjunctiveOperator right=Equality)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.left=current}
		public Action getBinaryLeftAction_1_0() { return cBinaryLeftAction_1_0; }

		//operator=ConjunctiveOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//ConjunctiveOperator
		public RuleCall getOperatorConjunctiveOperatorEnumRuleCall_1_1_0() { return cOperatorConjunctiveOperatorEnumRuleCall_1_1_0; }

		//right=Equality
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Equality
		public RuleCall getRightEqualityParserRuleCall_1_2_0() { return cRightEqualityParserRuleCall_1_2_0; }
	}

	public class EqualityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Equality");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cComparativeParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorEqualityOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightComparativeParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Equality returns Expression:
		//	Comparative ({Binary.left=current} operator=EqualityOperator right=Comparative)*;
		public ParserRule getRule() { return rule; }

		//Comparative ({Binary.left=current} operator=EqualityOperator right=Comparative)*
		public Group getGroup() { return cGroup; }

		//Comparative
		public RuleCall getComparativeParserRuleCall_0() { return cComparativeParserRuleCall_0; }

		//({Binary.left=current} operator=EqualityOperator right=Comparative)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.left=current}
		public Action getBinaryLeftAction_1_0() { return cBinaryLeftAction_1_0; }

		//operator=EqualityOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//EqualityOperator
		public RuleCall getOperatorEqualityOperatorEnumRuleCall_1_1_0() { return cOperatorEqualityOperatorEnumRuleCall_1_1_0; }

		//right=Comparative
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Comparative
		public RuleCall getRightComparativeParserRuleCall_1_2_0() { return cRightComparativeParserRuleCall_1_2_0; }
	}

	public class ComparativeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Comparative");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAdditiveParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorComparativeOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAdditiveParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Comparative returns Expression:
		//	Additive ({Binary.left=current} operator=ComparativeOperator right=Additive)*;
		public ParserRule getRule() { return rule; }

		//Additive ({Binary.left=current} operator=ComparativeOperator right=Additive)*
		public Group getGroup() { return cGroup; }

		//Additive
		public RuleCall getAdditiveParserRuleCall_0() { return cAdditiveParserRuleCall_0; }

		//({Binary.left=current} operator=ComparativeOperator right=Additive)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.left=current}
		public Action getBinaryLeftAction_1_0() { return cBinaryLeftAction_1_0; }

		//operator=ComparativeOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//ComparativeOperator
		public RuleCall getOperatorComparativeOperatorEnumRuleCall_1_1_0() { return cOperatorComparativeOperatorEnumRuleCall_1_1_0; }

		//right=Additive
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Additive
		public RuleCall getRightAdditiveParserRuleCall_1_2_0() { return cRightAdditiveParserRuleCall_1_2_0; }
	}

	public class AdditiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Additive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicativeParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorAdditiveOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightMultiplicativeParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Additive returns Expression:
		//	Multiplicative ({Binary.left=current} operator=AdditiveOperator right=Multiplicative)*;
		public ParserRule getRule() { return rule; }

		//Multiplicative ({Binary.left=current} operator=AdditiveOperator right=Multiplicative)*
		public Group getGroup() { return cGroup; }

		//Multiplicative
		public RuleCall getMultiplicativeParserRuleCall_0() { return cMultiplicativeParserRuleCall_0; }

		//({Binary.left=current} operator=AdditiveOperator right=Multiplicative)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.left=current}
		public Action getBinaryLeftAction_1_0() { return cBinaryLeftAction_1_0; }

		//operator=AdditiveOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//AdditiveOperator
		public RuleCall getOperatorAdditiveOperatorEnumRuleCall_1_1_0() { return cOperatorAdditiveOperatorEnumRuleCall_1_1_0; }

		//right=Multiplicative
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Multiplicative
		public RuleCall getRightMultiplicativeParserRuleCall_1_2_0() { return cRightMultiplicativeParserRuleCall_1_2_0; }
	}

	public class MultiplicativeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Multiplicative");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimitiveParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorMultiplicativeOperatorEnumRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimitiveParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Multiplicative returns Expression:
		//	Primitive ({Binary.left=current} operator=MultiplicativeOperator right=Primitive)*;
		public ParserRule getRule() { return rule; }

		//Primitive ({Binary.left=current} operator=MultiplicativeOperator right=Primitive)*
		public Group getGroup() { return cGroup; }

		//Primitive
		public RuleCall getPrimitiveParserRuleCall_0() { return cPrimitiveParserRuleCall_0; }

		//({Binary.left=current} operator=MultiplicativeOperator right=Primitive)*
		public Group getGroup_1() { return cGroup_1; }

		//{Binary.left=current}
		public Action getBinaryLeftAction_1_0() { return cBinaryLeftAction_1_0; }

		//operator=MultiplicativeOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }

		//MultiplicativeOperator
		public RuleCall getOperatorMultiplicativeOperatorEnumRuleCall_1_1_0() { return cOperatorMultiplicativeOperatorEnumRuleCall_1_1_0; }

		//right=Primitive
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Primitive
		public RuleCall getRightPrimitiveParserRuleCall_1_2_0() { return cRightPrimitiveParserRuleCall_1_2_0; }
	}

	public class PrimitiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Primitive");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cUnaryParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cScalarParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInRangeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cIntegerParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDoubleParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cBooleanParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cString0ParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cIdentifierParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final Group cGroup_8 = (Group)cAlternatives.eContents().get(8);
		private final Keyword cLeftParenthesisKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_8_1 = (RuleCall)cGroup_8.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8_2 = (Keyword)cGroup_8.eContents().get(2);
		
		//Primitive returns Expression:
		//	Unary | Scalar | InRange | Integer | Double | Boolean | String0 | Identifier | "(" Expression ")";
		public ParserRule getRule() { return rule; }

		//Unary | Scalar | InRange | Integer | Double | Boolean | String0 | Identifier | "(" Expression ")"
		public Alternatives getAlternatives() { return cAlternatives; }

		//Unary
		public RuleCall getUnaryParserRuleCall_0() { return cUnaryParserRuleCall_0; }

		//Scalar
		public RuleCall getScalarParserRuleCall_1() { return cScalarParserRuleCall_1; }

		//InRange
		public RuleCall getInRangeParserRuleCall_2() { return cInRangeParserRuleCall_2; }

		//Integer
		public RuleCall getIntegerParserRuleCall_3() { return cIntegerParserRuleCall_3; }

		//Double
		public RuleCall getDoubleParserRuleCall_4() { return cDoubleParserRuleCall_4; }

		//Boolean
		public RuleCall getBooleanParserRuleCall_5() { return cBooleanParserRuleCall_5; }

		//String0
		public RuleCall getString0ParserRuleCall_6() { return cString0ParserRuleCall_6; }

		//Identifier
		public RuleCall getIdentifierParserRuleCall_7() { return cIdentifierParserRuleCall_7; }

		//"(" Expression ")"
		public Group getGroup_8() { return cGroup_8; }

		//"("
		public Keyword getLeftParenthesisKeyword_8_0() { return cLeftParenthesisKeyword_8_0; }

		//Expression
		public RuleCall getExpressionParserRuleCall_8_1() { return cExpressionParserRuleCall_8_1; }

		//")"
		public Keyword getRightParenthesisKeyword_8_2() { return cRightParenthesisKeyword_8_2; }
	}

	public class UnaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Unary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperatorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOperatorUnaryOperatorEnumRuleCall_0_0 = (RuleCall)cOperatorAssignment_0.eContents().get(0);
		private final Assignment cInnerAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInnerPrimitiveParserRuleCall_1_0 = (RuleCall)cInnerAssignment_1.eContents().get(0);
		
		//Unary:
		//	operator=UnaryOperator inner=Primitive;
		public ParserRule getRule() { return rule; }

		//operator=UnaryOperator inner=Primitive
		public Group getGroup() { return cGroup; }

		//operator=UnaryOperator
		public Assignment getOperatorAssignment_0() { return cOperatorAssignment_0; }

		//UnaryOperator
		public RuleCall getOperatorUnaryOperatorEnumRuleCall_0_0() { return cOperatorUnaryOperatorEnumRuleCall_0_0; }

		//inner=Primitive
		public Assignment getInnerAssignment_1() { return cInnerAssignment_1; }

		//Primitive
		public RuleCall getInnerPrimitiveParserRuleCall_1_0() { return cInnerPrimitiveParserRuleCall_1_0; }
	}

	public class ScalarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Scalar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperatorAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOperatorScalarOperatorEnumRuleCall_0_0 = (RuleCall)cOperatorAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cIdParameterGroupCrossReference_2_0 = (CrossReference)cIdAssignment_2.eContents().get(0);
		private final RuleCall cIdParameterGroupIDTerminalRuleCall_2_0_1 = (RuleCall)cIdParameterGroupCrossReference_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Scalar:
		//	operator=ScalarOperator "(" id=[ParameterGroup] ")";
		public ParserRule getRule() { return rule; }

		//operator=ScalarOperator "(" id=[ParameterGroup] ")"
		public Group getGroup() { return cGroup; }

		//operator=ScalarOperator
		public Assignment getOperatorAssignment_0() { return cOperatorAssignment_0; }

		//ScalarOperator
		public RuleCall getOperatorScalarOperatorEnumRuleCall_0_0() { return cOperatorScalarOperatorEnumRuleCall_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//id=[ParameterGroup]
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }

		//[ParameterGroup]
		public CrossReference getIdParameterGroupCrossReference_2_0() { return cIdParameterGroupCrossReference_2_0; }

		//ID
		public RuleCall getIdParameterGroupIDTerminalRuleCall_2_0_1() { return cIdParameterGroupIDTerminalRuleCall_2_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}

	public class ConstantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constant");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntegerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDoubleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBooleanParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cString0ParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Constant:
		//	Integer | Double | Boolean | String0;
		public ParserRule getRule() { return rule; }

		//Integer | Double | Boolean | String0
		public Alternatives getAlternatives() { return cAlternatives; }

		//Integer
		public RuleCall getIntegerParserRuleCall_0() { return cIntegerParserRuleCall_0; }

		//Double
		public RuleCall getDoubleParserRuleCall_1() { return cDoubleParserRuleCall_1; }

		//Boolean
		public RuleCall getBooleanParserRuleCall_2() { return cBooleanParserRuleCall_2; }

		//String0
		public RuleCall getString0ParserRuleCall_3() { return cString0ParserRuleCall_3; }
	}

	public class InRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cParameterAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cParameterParameterCrossReference_0_0 = (CrossReference)cParameterAssignment_0.eContents().get(0);
		private final RuleCall cParameterParameterIDTerminalRuleCall_0_0_1 = (RuleCall)cParameterParameterCrossReference_0_0.eContents().get(1);
		private final Keyword cInKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRangeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRangeValueRangeParserRuleCall_2_0 = (RuleCall)cRangeAssignment_2.eContents().get(0);
		
		//InRange:
		//	parameter=[Parameter] "in" range=ValueRange;
		public ParserRule getRule() { return rule; }

		//parameter=[Parameter] "in" range=ValueRange
		public Group getGroup() { return cGroup; }

		//parameter=[Parameter]
		public Assignment getParameterAssignment_0() { return cParameterAssignment_0; }

		//[Parameter]
		public CrossReference getParameterParameterCrossReference_0_0() { return cParameterParameterCrossReference_0_0; }

		//ID
		public RuleCall getParameterParameterIDTerminalRuleCall_0_0_1() { return cParameterParameterIDTerminalRuleCall_0_0_1; }

		//"in"
		public Keyword getInKeyword_1() { return cInKeyword_1; }

		//range=ValueRange
		public Assignment getRangeAssignment_2() { return cRangeAssignment_2; }

		//ValueRange
		public RuleCall getRangeValueRangeParserRuleCall_2_0() { return cRangeValueRangeParserRuleCall_2_0; }
	}

	public class IntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Integer");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Integer:
		//	value=EInt;
		public ParserRule getRule() { return rule; }

		//value=EInt
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EInt
		public RuleCall getValueEIntParserRuleCall_0() { return cValueEIntParserRuleCall_0; }
	}

	public class DoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Double");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEDoubleParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Double:
		//	value=EDouble;
		public ParserRule getRule() { return rule; }

		//value=EDouble
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EDouble
		public RuleCall getValueEDoubleParserRuleCall_0() { return cValueEDoubleParserRuleCall_0; }
	}

	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Boolean");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEBooleanParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//Boolean:
		//	value=EBoolean;
		public ParserRule getRule() { return rule; }

		//value=EBoolean
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_0() { return cValueEBooleanParserRuleCall_0; }
	}

	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "String0");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//String0 returns String:
		//	value=STRING;
		public ParserRule getRule() { return rule; }

		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}

	public class IdentifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Identifier");
		private final Assignment cIdAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cIdParameterCrossReference_0 = (CrossReference)cIdAssignment.eContents().get(0);
		private final RuleCall cIdParameterIDTerminalRuleCall_0_1 = (RuleCall)cIdParameterCrossReference_0.eContents().get(1);
		
		//Identifier:
		//	id=[Parameter];
		public ParserRule getRule() { return rule; }

		//id=[Parameter]
		public Assignment getIdAssignment() { return cIdAssignment; }

		//[Parameter]
		public CrossReference getIdParameterCrossReference_0() { return cIdParameterCrossReference_0; }

		//ID
		public RuleCall getIdParameterIDTerminalRuleCall_0_1() { return cIdParameterIDTerminalRuleCall_0_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EInt returns ecore::EInt: / * '-'? * / INT;
		public ParserRule getRule() { return rule; }

		/// * '-'? * / INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}

	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_3_0 = (Alternatives)cGroup_3.eContents().get(0);
		private final Keyword cEKeyword_3_0_0 = (Keyword)cAlternatives_3_0.eContents().get(0);
		private final Keyword cEKeyword_3_0_1 = (Keyword)cAlternatives_3_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_3_2 = (RuleCall)cGroup_3.eContents().get(2);
		
		//EDouble returns ecore::EDouble: / * '-'? * / INT? "." INT (("E" | "e") "-"? INT)?;
		public ParserRule getRule() { return rule; }

		/// * '-'? * / INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup() { return cGroup; }

		/// * '-'? * / INT?
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_3() { return cGroup_3; }

		//"E" | "e"
		public Alternatives getAlternatives_3_0() { return cAlternatives_3_0; }

		//"E"
		public Keyword getEKeyword_3_0_0() { return cEKeyword_3_0_0; }

		//"e"
		public Keyword getEKeyword_3_0_1() { return cEKeyword_3_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_3_1() { return cHyphenMinusKeyword_3_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_3_2() { return cINTTerminalRuleCall_3_2; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	public class DisjunctiveOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "DisjunctiveOperator");
		private final EnumLiteralDeclaration cDisjunctionEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cDisjunctionOrKeyword_0 = (Keyword)cDisjunctionEnumLiteralDeclaration.eContents().get(0);
		
		//enum DisjunctiveOperator returns BinaryOperator:
		//	disjunction="or";
		public EnumRule getRule() { return rule; }

		//disjunction="or"
		public EnumLiteralDeclaration getDisjunctionEnumLiteralDeclaration() { return cDisjunctionEnumLiteralDeclaration; }

		//"or"
		public Keyword getDisjunctionOrKeyword_0() { return cDisjunctionOrKeyword_0; }
	}

	public class ConjunctiveOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ConjunctiveOperator");
		private final EnumLiteralDeclaration cConjunctionEnumLiteralDeclaration = (EnumLiteralDeclaration)rule.eContents().get(1);
		private final Keyword cConjunctionAndKeyword_0 = (Keyword)cConjunctionEnumLiteralDeclaration.eContents().get(0);
		
		//enum ConjunctiveOperator returns BinaryOperator:
		//	conjunction="and";
		public EnumRule getRule() { return rule; }

		//conjunction="and"
		public EnumLiteralDeclaration getConjunctionEnumLiteralDeclaration() { return cConjunctionEnumLiteralDeclaration; }

		//"and"
		public Keyword getConjunctionAndKeyword_0() { return cConjunctionAndKeyword_0; }
	}

	public class EqualityOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "EqualityOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEqualEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEqualEqualsSignEqualsSignKeyword_0_0 = (Keyword)cEqualEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNotEqualEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNotEqualExclamationMarkEqualsSignKeyword_1_0 = (Keyword)cNotEqualEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum EqualityOperator returns BinaryOperator:
		//	equal="==" | notEqual="!=";
		public EnumRule getRule() { return rule; }

		//equal="==" | notEqual="!="
		public Alternatives getAlternatives() { return cAlternatives; }

		//equal="=="
		public EnumLiteralDeclaration getEqualEnumLiteralDeclaration_0() { return cEqualEnumLiteralDeclaration_0; }

		//"=="
		public Keyword getEqualEqualsSignEqualsSignKeyword_0_0() { return cEqualEqualsSignEqualsSignKeyword_0_0; }

		//notEqual="!="
		public EnumLiteralDeclaration getNotEqualEnumLiteralDeclaration_1() { return cNotEqualEnumLiteralDeclaration_1; }

		//"!="
		public Keyword getNotEqualExclamationMarkEqualsSignKeyword_1_0() { return cNotEqualExclamationMarkEqualsSignKeyword_1_0; }
	}

	public class ComparativeOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ComparativeOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLessThanEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLessThanLessThanSignKeyword_0_0 = (Keyword)cLessThanEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLessThanEqualEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLessThanEqualLessThanSignEqualsSignKeyword_1_0 = (Keyword)cLessThanEqualEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGreaterThanEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGreaterThanGreaterThanSignKeyword_2_0 = (Keyword)cGreaterThanEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cGreaterThanEqualEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cGreaterThanEqualGreaterThanSignEqualsSignKeyword_3_0 = (Keyword)cGreaterThanEqualEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ComparativeOperator returns BinaryOperator:
		//	lessThan="<" | lessThanEqual="<=" | greaterThan=">" | greaterThanEqual=">=";
		public EnumRule getRule() { return rule; }

		//lessThan="<" | lessThanEqual="<=" | greaterThan=">" | greaterThanEqual=">="
		public Alternatives getAlternatives() { return cAlternatives; }

		//lessThan="<"
		public EnumLiteralDeclaration getLessThanEnumLiteralDeclaration_0() { return cLessThanEnumLiteralDeclaration_0; }

		//"<"
		public Keyword getLessThanLessThanSignKeyword_0_0() { return cLessThanLessThanSignKeyword_0_0; }

		//lessThanEqual="<="
		public EnumLiteralDeclaration getLessThanEqualEnumLiteralDeclaration_1() { return cLessThanEqualEnumLiteralDeclaration_1; }

		//"<="
		public Keyword getLessThanEqualLessThanSignEqualsSignKeyword_1_0() { return cLessThanEqualLessThanSignEqualsSignKeyword_1_0; }

		//greaterThan=">"
		public EnumLiteralDeclaration getGreaterThanEnumLiteralDeclaration_2() { return cGreaterThanEnumLiteralDeclaration_2; }

		//">"
		public Keyword getGreaterThanGreaterThanSignKeyword_2_0() { return cGreaterThanGreaterThanSignKeyword_2_0; }

		//greaterThanEqual=">="
		public EnumLiteralDeclaration getGreaterThanEqualEnumLiteralDeclaration_3() { return cGreaterThanEqualEnumLiteralDeclaration_3; }

		//">="
		public Keyword getGreaterThanEqualGreaterThanSignEqualsSignKeyword_3_0() { return cGreaterThanEqualGreaterThanSignEqualsSignKeyword_3_0; }
	}

	public class AdditiveOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "AdditiveOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAdditionEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAdditionPlusSignKeyword_0_0 = (Keyword)cAdditionEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSubtractionEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSubtractionHyphenMinusKeyword_1_0 = (Keyword)cSubtractionEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum AdditiveOperator returns BinaryOperator:
		//	addition="+" | subtraction="-";
		public EnumRule getRule() { return rule; }

		//addition="+" | subtraction="-"
		public Alternatives getAlternatives() { return cAlternatives; }

		//addition="+"
		public EnumLiteralDeclaration getAdditionEnumLiteralDeclaration_0() { return cAdditionEnumLiteralDeclaration_0; }

		//"+"
		public Keyword getAdditionPlusSignKeyword_0_0() { return cAdditionPlusSignKeyword_0_0; }

		//subtraction="-"
		public EnumLiteralDeclaration getSubtractionEnumLiteralDeclaration_1() { return cSubtractionEnumLiteralDeclaration_1; }

		//"-"
		public Keyword getSubtractionHyphenMinusKeyword_1_0() { return cSubtractionHyphenMinusKeyword_1_0; }
	}

	public class MultiplicativeOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "MultiplicativeOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMultiplicationEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMultiplicationAsteriskKeyword_0_0 = (Keyword)cMultiplicationEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDivisionEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDivisionSolidusKeyword_1_0 = (Keyword)cDivisionEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum MultiplicativeOperator returns BinaryOperator:
		//	multiplication="*" | division="/";
		public EnumRule getRule() { return rule; }

		//multiplication="*" | division="/"
		public Alternatives getAlternatives() { return cAlternatives; }

		//multiplication="*"
		public EnumLiteralDeclaration getMultiplicationEnumLiteralDeclaration_0() { return cMultiplicationEnumLiteralDeclaration_0; }

		//"*"
		public Keyword getMultiplicationAsteriskKeyword_0_0() { return cMultiplicationAsteriskKeyword_0_0; }

		//division="/"
		public EnumLiteralDeclaration getDivisionEnumLiteralDeclaration_1() { return cDivisionEnumLiteralDeclaration_1; }

		//"/"
		public Keyword getDivisionSolidusKeyword_1_0() { return cDivisionSolidusKeyword_1_0; }
	}

	public class UnaryOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "UnaryOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cInversionEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cInversionNotKeyword_0_0 = (Keyword)cInversionEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNegationEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNegationHyphenMinusKeyword_1_0 = (Keyword)cNegationEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum UnaryOperator:
		//	inversion="not" | negation="-";
		public EnumRule getRule() { return rule; }

		//inversion="not" | negation="-"
		public Alternatives getAlternatives() { return cAlternatives; }

		//inversion="not"
		public EnumLiteralDeclaration getInversionEnumLiteralDeclaration_0() { return cInversionEnumLiteralDeclaration_0; }

		//"not"
		public Keyword getInversionNotKeyword_0_0() { return cInversionNotKeyword_0_0; }

		//negation="-"
		public EnumLiteralDeclaration getNegationEnumLiteralDeclaration_1() { return cNegationEnumLiteralDeclaration_1; }

		//"-"
		public Keyword getNegationHyphenMinusKeyword_1_0() { return cNegationHyphenMinusKeyword_1_0; }
	}

	public class ScalarOperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ScalarOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSumEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSumSumKeyword_0_0 = (Keyword)cSumEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMinEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMinMinKeyword_1_0 = (Keyword)cMinEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMaxEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMaxMaxKeyword_2_0 = (Keyword)cMaxEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ScalarOperator:
		//	sum | min | max;
		public EnumRule getRule() { return rule; }

		//sum | min | max
		public Alternatives getAlternatives() { return cAlternatives; }

		//sum
		public EnumLiteralDeclaration getSumEnumLiteralDeclaration_0() { return cSumEnumLiteralDeclaration_0; }

		//"sum"
		public Keyword getSumSumKeyword_0_0() { return cSumSumKeyword_0_0; }

		//min
		public EnumLiteralDeclaration getMinEnumLiteralDeclaration_1() { return cMinEnumLiteralDeclaration_1; }

		//"min"
		public Keyword getMinMinKeyword_1_0() { return cMinMinKeyword_1_0; }

		//max
		public EnumLiteralDeclaration getMaxEnumLiteralDeclaration_2() { return cMaxEnumLiteralDeclaration_2; }

		//"max"
		public Keyword getMaxMaxKeyword_2_0() { return cMaxMaxKeyword_2_0; }
	}
	
	private ConfiguratorElements pConfigurator;
	private AbstractParameterElements pAbstractParameter;
	private ParameterGroupElements pParameterGroup;
	private ParameterElements pParameter;
	private ValueRangeElements pValueRange;
	private EnumeratedElements pEnumerated;
	private BoundedElements pBounded;
	private ConstraintElements pConstraint;
	private ExpressionElements pExpression;
	private DisjunctiveOperatorElements unknownRuleDisjunctiveOperator;
	private DisjunctiveElements pDisjunctive;
	private ConjunctiveOperatorElements unknownRuleConjunctiveOperator;
	private ConjunctiveElements pConjunctive;
	private EqualityOperatorElements unknownRuleEqualityOperator;
	private EqualityElements pEquality;
	private ComparativeOperatorElements unknownRuleComparativeOperator;
	private ComparativeElements pComparative;
	private AdditiveOperatorElements unknownRuleAdditiveOperator;
	private AdditiveElements pAdditive;
	private MultiplicativeOperatorElements unknownRuleMultiplicativeOperator;
	private MultiplicativeElements pMultiplicative;
	private PrimitiveElements pPrimitive;
	private UnaryOperatorElements unknownRuleUnaryOperator;
	private UnaryElements pUnary;
	private ScalarOperatorElements unknownRuleScalarOperator;
	private ScalarElements pScalar;
	private ConstantElements pConstant;
	private InRangeElements pInRange;
	private IntegerElements pInteger;
	private DoubleElements pDouble;
	private BooleanElements pBoolean;
	private String0Elements pString0;
	private IdentifierElements pIdentifier;
	private EIntElements pEInt;
	private EDoubleElements pEDouble;
	private EBooleanElements pEBoolean;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ConfiguratorGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.itu.smdp2015.church.Configurator".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Configurator:
	//	"configurator" name=ID description=STRING? "{" parameters+=AbstractParameter (","? parameters+=AbstractParameter)*
	//	"}";
	public ConfiguratorElements getConfiguratorAccess() {
		return (pConfigurator != null) ? pConfigurator : (pConfigurator = new ConfiguratorElements());
	}
	
	public ParserRule getConfiguratorRule() {
		return getConfiguratorAccess().getRule();
	}

	//AbstractParameter:
	//	ParameterGroup | Parameter;
	public AbstractParameterElements getAbstractParameterAccess() {
		return (pAbstractParameter != null) ? pAbstractParameter : (pAbstractParameter = new AbstractParameterElements());
	}
	
	public ParserRule getAbstractParameterRule() {
		return getAbstractParameterAccess().getRule();
	}

	//ParameterGroup:
	//	"group" name=ID description=STRING? (("visible-if" visibility=Expression)? & ("constraints" "{"
	//	constraints+=Constraint ("," constraints+=Constraint)* ","? "}")? & "{" parameters+=AbstractParameter (","?
	//	parameters+=AbstractParameter)* ","? "}");
	public ParameterGroupElements getParameterGroupAccess() {
		return (pParameterGroup != null) ? pParameterGroup : (pParameterGroup = new ParameterGroupElements());
	}
	
	public ParserRule getParameterGroupRule() {
		return getParameterGroupAccess().getRule();
	}

	//Parameter:
	//	"parameter" name=ID description=STRING? ((mandatory?="mandatory" | "optional")? & ("visible-if"
	//	visibility=Expression)? & ("constraints" "{" constraints+=Constraint ("," constraints+=Constraint)* "}")? & "values"
	//	valueRange=ValueRange);
	public ParameterElements getParameterAccess() {
		return (pParameter != null) ? pParameter : (pParameter = new ParameterElements());
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//ValueRange:
	//	Enumerated | Bounded;
	public ValueRangeElements getValueRangeAccess() {
		return (pValueRange != null) ? pValueRange : (pValueRange = new ValueRangeElements());
	}
	
	public ParserRule getValueRangeRule() {
		return getValueRangeAccess().getRule();
	}

	//Enumerated:
	//	"(" values+=Expression ("," values+=Expression)* ")";
	public EnumeratedElements getEnumeratedAccess() {
		return (pEnumerated != null) ? pEnumerated : (pEnumerated = new EnumeratedElements());
	}
	
	public ParserRule getEnumeratedRule() {
		return getEnumeratedAccess().getRule();
	}

	//Bounded:
	//	"[" lowerBound=Expression ";" upperBound=Expression "]";
	public BoundedElements getBoundedAccess() {
		return (pBounded != null) ? pBounded : (pBounded = new BoundedElements());
	}
	
	public ParserRule getBoundedRule() {
		return getBoundedAccess().getRule();
	}

	//Constraint:
	//	("description" description=STRING)? expr=Expression;
	public ConstraintElements getConstraintAccess() {
		return (pConstraint != null) ? pConstraint : (pConstraint = new ConstraintElements());
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}

	//Expression:
	//	Disjunctive;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//enum DisjunctiveOperator returns BinaryOperator:
	//	disjunction="or";
	public DisjunctiveOperatorElements getDisjunctiveOperatorAccess() {
		return (unknownRuleDisjunctiveOperator != null) ? unknownRuleDisjunctiveOperator : (unknownRuleDisjunctiveOperator = new DisjunctiveOperatorElements());
	}
	
	public EnumRule getDisjunctiveOperatorRule() {
		return getDisjunctiveOperatorAccess().getRule();
	}

	//Disjunctive returns Expression:
	//	Conjunctive ({Binary.left=current} operator=DisjunctiveOperator right=Conjunctive)*;
	public DisjunctiveElements getDisjunctiveAccess() {
		return (pDisjunctive != null) ? pDisjunctive : (pDisjunctive = new DisjunctiveElements());
	}
	
	public ParserRule getDisjunctiveRule() {
		return getDisjunctiveAccess().getRule();
	}

	//enum ConjunctiveOperator returns BinaryOperator:
	//	conjunction="and";
	public ConjunctiveOperatorElements getConjunctiveOperatorAccess() {
		return (unknownRuleConjunctiveOperator != null) ? unknownRuleConjunctiveOperator : (unknownRuleConjunctiveOperator = new ConjunctiveOperatorElements());
	}
	
	public EnumRule getConjunctiveOperatorRule() {
		return getConjunctiveOperatorAccess().getRule();
	}

	//Conjunctive returns Expression:
	//	Equality ({Binary.left=current} operator=ConjunctiveOperator right=Equality)*;
	public ConjunctiveElements getConjunctiveAccess() {
		return (pConjunctive != null) ? pConjunctive : (pConjunctive = new ConjunctiveElements());
	}
	
	public ParserRule getConjunctiveRule() {
		return getConjunctiveAccess().getRule();
	}

	//enum EqualityOperator returns BinaryOperator:
	//	equal="==" | notEqual="!=";
	public EqualityOperatorElements getEqualityOperatorAccess() {
		return (unknownRuleEqualityOperator != null) ? unknownRuleEqualityOperator : (unknownRuleEqualityOperator = new EqualityOperatorElements());
	}
	
	public EnumRule getEqualityOperatorRule() {
		return getEqualityOperatorAccess().getRule();
	}

	//Equality returns Expression:
	//	Comparative ({Binary.left=current} operator=EqualityOperator right=Comparative)*;
	public EqualityElements getEqualityAccess() {
		return (pEquality != null) ? pEquality : (pEquality = new EqualityElements());
	}
	
	public ParserRule getEqualityRule() {
		return getEqualityAccess().getRule();
	}

	//enum ComparativeOperator returns BinaryOperator:
	//	lessThan="<" | lessThanEqual="<=" | greaterThan=">" | greaterThanEqual=">=";
	public ComparativeOperatorElements getComparativeOperatorAccess() {
		return (unknownRuleComparativeOperator != null) ? unknownRuleComparativeOperator : (unknownRuleComparativeOperator = new ComparativeOperatorElements());
	}
	
	public EnumRule getComparativeOperatorRule() {
		return getComparativeOperatorAccess().getRule();
	}

	//Comparative returns Expression:
	//	Additive ({Binary.left=current} operator=ComparativeOperator right=Additive)*;
	public ComparativeElements getComparativeAccess() {
		return (pComparative != null) ? pComparative : (pComparative = new ComparativeElements());
	}
	
	public ParserRule getComparativeRule() {
		return getComparativeAccess().getRule();
	}

	//enum AdditiveOperator returns BinaryOperator:
	//	addition="+" | subtraction="-";
	public AdditiveOperatorElements getAdditiveOperatorAccess() {
		return (unknownRuleAdditiveOperator != null) ? unknownRuleAdditiveOperator : (unknownRuleAdditiveOperator = new AdditiveOperatorElements());
	}
	
	public EnumRule getAdditiveOperatorRule() {
		return getAdditiveOperatorAccess().getRule();
	}

	//Additive returns Expression:
	//	Multiplicative ({Binary.left=current} operator=AdditiveOperator right=Multiplicative)*;
	public AdditiveElements getAdditiveAccess() {
		return (pAdditive != null) ? pAdditive : (pAdditive = new AdditiveElements());
	}
	
	public ParserRule getAdditiveRule() {
		return getAdditiveAccess().getRule();
	}

	//enum MultiplicativeOperator returns BinaryOperator:
	//	multiplication="*" | division="/";
	public MultiplicativeOperatorElements getMultiplicativeOperatorAccess() {
		return (unknownRuleMultiplicativeOperator != null) ? unknownRuleMultiplicativeOperator : (unknownRuleMultiplicativeOperator = new MultiplicativeOperatorElements());
	}
	
	public EnumRule getMultiplicativeOperatorRule() {
		return getMultiplicativeOperatorAccess().getRule();
	}

	//Multiplicative returns Expression:
	//	Primitive ({Binary.left=current} operator=MultiplicativeOperator right=Primitive)*;
	public MultiplicativeElements getMultiplicativeAccess() {
		return (pMultiplicative != null) ? pMultiplicative : (pMultiplicative = new MultiplicativeElements());
	}
	
	public ParserRule getMultiplicativeRule() {
		return getMultiplicativeAccess().getRule();
	}

	//Primitive returns Expression:
	//	Unary | Scalar | InRange | Integer | Double | Boolean | String0 | Identifier | "(" Expression ")";
	public PrimitiveElements getPrimitiveAccess() {
		return (pPrimitive != null) ? pPrimitive : (pPrimitive = new PrimitiveElements());
	}
	
	public ParserRule getPrimitiveRule() {
		return getPrimitiveAccess().getRule();
	}

	//enum UnaryOperator:
	//	inversion="not" | negation="-";
	public UnaryOperatorElements getUnaryOperatorAccess() {
		return (unknownRuleUnaryOperator != null) ? unknownRuleUnaryOperator : (unknownRuleUnaryOperator = new UnaryOperatorElements());
	}
	
	public EnumRule getUnaryOperatorRule() {
		return getUnaryOperatorAccess().getRule();
	}

	//Unary:
	//	operator=UnaryOperator inner=Primitive;
	public UnaryElements getUnaryAccess() {
		return (pUnary != null) ? pUnary : (pUnary = new UnaryElements());
	}
	
	public ParserRule getUnaryRule() {
		return getUnaryAccess().getRule();
	}

	//enum ScalarOperator:
	//	sum | min | max;
	public ScalarOperatorElements getScalarOperatorAccess() {
		return (unknownRuleScalarOperator != null) ? unknownRuleScalarOperator : (unknownRuleScalarOperator = new ScalarOperatorElements());
	}
	
	public EnumRule getScalarOperatorRule() {
		return getScalarOperatorAccess().getRule();
	}

	//Scalar:
	//	operator=ScalarOperator "(" id=[ParameterGroup] ")";
	public ScalarElements getScalarAccess() {
		return (pScalar != null) ? pScalar : (pScalar = new ScalarElements());
	}
	
	public ParserRule getScalarRule() {
		return getScalarAccess().getRule();
	}

	//Constant:
	//	Integer | Double | Boolean | String0;
	public ConstantElements getConstantAccess() {
		return (pConstant != null) ? pConstant : (pConstant = new ConstantElements());
	}
	
	public ParserRule getConstantRule() {
		return getConstantAccess().getRule();
	}

	//InRange:
	//	parameter=[Parameter] "in" range=ValueRange;
	public InRangeElements getInRangeAccess() {
		return (pInRange != null) ? pInRange : (pInRange = new InRangeElements());
	}
	
	public ParserRule getInRangeRule() {
		return getInRangeAccess().getRule();
	}

	//Integer:
	//	value=EInt;
	public IntegerElements getIntegerAccess() {
		return (pInteger != null) ? pInteger : (pInteger = new IntegerElements());
	}
	
	public ParserRule getIntegerRule() {
		return getIntegerAccess().getRule();
	}

	//Double:
	//	value=EDouble;
	public DoubleElements getDoubleAccess() {
		return (pDouble != null) ? pDouble : (pDouble = new DoubleElements());
	}
	
	public ParserRule getDoubleRule() {
		return getDoubleAccess().getRule();
	}

	//Boolean:
	//	value=EBoolean;
	public BooleanElements getBooleanAccess() {
		return (pBoolean != null) ? pBoolean : (pBoolean = new BooleanElements());
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}

	//String0 returns String:
	//	value=STRING;
	public String0Elements getString0Access() {
		return (pString0 != null) ? pString0 : (pString0 = new String0Elements());
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}

	//Identifier:
	//	id=[Parameter];
	public IdentifierElements getIdentifierAccess() {
		return (pIdentifier != null) ? pIdentifier : (pIdentifier = new IdentifierElements());
	}
	
	public ParserRule getIdentifierRule() {
		return getIdentifierAccess().getRule();
	}

	//EInt returns ecore::EInt: / * '-'? * / INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//EDouble returns ecore::EDouble: / * '-'? * / INT? "." INT (("E" | "e") "-"? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return (pEDouble != null) ? pEDouble : (pEDouble = new EDoubleElements());
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
