/*
 * generated by Xtext
 */
package dk.itu.smdp2015.church.ui.contentassist

import dk.itu.smdp2015.church.ui.contentassist.AbstractConfiguratorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ConfiguratorProposalProvider extends AbstractConfiguratorProposalProvider {
}
