/*
 * generated by Xtext
 */
package dk.itu.smdp2015.church.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.smdp2015.church.ui.internal.ConfiguratorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConfiguratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConfiguratorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConfiguratorActivator.getInstance().getInjector(ConfiguratorActivator.DK_ITU_SMDP2015_CHURCH_CONFIGURATOR);
	}
	
}
