/**
 * generated by Xtext
 */
package dk.itu.smdp2015.church.serializer;

import dk.itu.smdp2015.church.serializer.AbstractConfiguratorSemanticSequencer;

@SuppressWarnings("all")
public class ConfiguratorSemanticSequencer extends AbstractConfiguratorSemanticSequencer {
}
