/**
 * generated by Xtext
 */
package dk.itu.smdp2015.church.serializer;

import dk.itu.smdp2015.church.serializer.AbstractConfiguratorSyntacticSequencer;

@SuppressWarnings("all")
public class ConfiguratorSyntacticSequencer extends AbstractConfiguratorSyntacticSequencer {
}
