/*
 * generated by Xtext
 */
package dk.itu.smdp2015.church.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfiguratorUiModule extends dk.itu.smdp2015.church.ui.AbstractConfiguratorUiModule {
	public ConfiguratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
